"""
nayantra/core/models.py

Schemas for everything the Nayantra Core owns: maps, waypoints (= nav-graph
vertices), lanes, zones, fleets, robots, live robot state, tasks, traffic and
events. These are the single source of truth for the REST API, the WebSocket
stream, the MCP tools and persistence.

All ids are short slugs so they read well in logs and explanations
("UGV-03 is waiting for lane L12 held by UGV-01").
"""

from __future__ import annotations

import re
import time
import uuid
from enum import StrEnum
from typing import Annotated, Any, Literal

from pydantic import AfterValidator, BaseModel, ConfigDict, Field, field_validator, model_validator

_ID_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_.\-]{0,63}$")


def new_id(prefix: str) -> str:
    return f"{prefix}_{uuid.uuid4().hex[:8]}"


def slugify(text: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "_", text.strip().lower()).strip("_")
    return slug[:64] or "item"


def _check_id(value: str) -> str:
    if not _ID_RE.match(value):
        raise ValueError(
            f"invalid id {value!r}: use 1-64 letters, digits, '_', '-' or '.', "
            "starting with a letter or digit"
        )
    return value


SlugId = Annotated[str, AfterValidator(_check_id)]


class Schema(BaseModel):
    """Base for API-facing models: reject unknown fields so typos surface."""

    model_config = ConfigDict(extra="forbid", use_enum_values=True)


# ---------------------------------------------------------------------------
# Enumerations
# ---------------------------------------------------------------------------


class RobotType(StrEnum):
    UGV = "ugv"
    UAV = "uav"
    QUADRUPED = "quadruped"
    HUMANOID = "humanoid"
    OTHER = "other"


# Known capabilities. Custom capabilities are allowed (any slug); these get
# first-class meaning in task requirements and the UI.
KNOWN_CAPABILITIES: dict[str, str] = {
    "navigate": "Navigate",
    "carry_payload": "Carry payload",
    "pick": "Pick",
    "drop": "Drop",
    "dock": "Dock",
    "charge": "Charge",
    "patrol": "Patrol",
    "inspect": "Inspect",
    "follow": "Follow",
    "manipulate": "Manipulate",
    "takeoff": "Take off",
    "land": "Land",
}


class WaypointType(StrEnum):
    LOCATION = "location"
    INTERSECTION = "intersection"
    CHARGER = "charger"
    PICKUP = "pickup"
    DROPOFF = "dropoff"
    DOCK = "dock"
    PARKING = "parking"
    LANDING_PAD = "landing_pad"
    INSPECTION = "inspection"


class ZoneType(StrEnum):
    RESTRICTED = "restricted"
    NO_FLY = "no_fly"
    SLOW = "slow"
    CHARGING = "charging"
    RECEIVING = "receiving"
    STORAGE = "storage"
    LOADING = "loading"
    PICKUP = "pickup"
    DROPOFF = "dropoff"
    FLEET_BOUNDARY = "fleet_boundary"
    CUSTOM = "custom"


class Layer(StrEnum):
    GROUND = "ground"
    AIR = "air"


class Protocol(StrEnum):
    SIMULATION = "simulation"
    ROS2 = "ros2"
    ISAAC_DEMO = "isaac_demo"
    MQTT = "mqtt"
    REST = "rest"
    WEBSOCKET = "websocket"
    CUSTOM = "custom"


class NavStack(StrEnum):
    NAV2 = "nav2"
    PX4 = "px4"
    ARDUPILOT = "ardupilot"
    KINEMATIC_SIM = "kinematic_sim"
    VENDOR = "vendor"
    CUSTOM = "custom"
    NONE = "none"


class Localization(StrEnum):
    AMCL = "amcl"
    SLAM_TOOLBOX = "slam_toolbox"
    CUVSLAM = "cuvslam"
    RTABMAP = "rtabmap"
    GPS = "gps"
    GROUND_TRUTH = "ground_truth"
    VENDOR = "vendor"
    NONE = "none"


class RobotMode(StrEnum):
    OFFLINE = "offline"
    IDLE = "idle"
    MOVING = "moving"
    WAITING = "waiting"  # held by traffic coordination
    PAUSED = "paused"
    CHARGING = "charging"
    ACTING = "acting"  # performing an action at a waypoint (pickup, dock …)
    ERROR = "error"
    EMERGENCY_STOP = "emergency_stop"


class TaskStatus(StrEnum):
    QUEUED = "queued"
    ASSIGNED = "assigned"
    PLANNING = "planning"
    EXECUTING = "executing"
    PAUSED = "paused"
    WAITING_FOR_TRAFFIC = "waiting_for_traffic"
    WAITING_FOR_ROBOT = "waiting_for_robot"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"


TERMINAL_TASK_STATUSES = frozenset({TaskStatus.COMPLETED, TaskStatus.FAILED, TaskStatus.CANCELLED})


class TaskType(StrEnum):
    NAVIGATE = "navigate"
    DELIVERY = "delivery"
    PATROL = "patrol"
    INSPECT = "inspect"
    CHARGE = "charge"
    DOCK = "dock"
    TAKEOFF = "takeoff"
    LAND = "land"
    MAKE_WAY = "make_way"  # system-generated by traffic negotiation


class Severity(StrEnum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


# ---------------------------------------------------------------------------
# Geometry primitives
# ---------------------------------------------------------------------------


class Pose(BaseModel):
    x: float = 0.0
    y: float = 0.0
    z: float = 0.0
    yaw: float = 0.0


class Bounds(BaseModel):
    min_x: float
    min_y: float
    max_x: float
    max_y: float

    @model_validator(mode="after")
    def _ordered(self) -> Bounds:
        if self.max_x <= self.min_x or self.max_y <= self.min_y:
            raise ValueError("bounds max must exceed min on both axes")
        return self

    def contains(self, x: float, y: float) -> bool:
        return self.min_x <= x <= self.max_x and self.min_y <= y <= self.max_y


Point2 = tuple[float, float]


# ---------------------------------------------------------------------------
# Maps, waypoints (graph vertices), lanes (graph edges), zones
# ---------------------------------------------------------------------------


class MapImage(BaseModel):
    """Occupancy/background image placed like a Nav2 map_server map."""

    url: str
    resolution: float = Field(0.05, gt=0, description="metres per pixel")
    origin: list[float] = Field(
        default_factory=lambda: [0.0, 0.0, 0.0],
        description="[x, y, yaw] of the image's lower-left pixel in the map frame",
    )
    width_px: int = Field(..., gt=0)
    height_px: int = Field(..., gt=0)
    opacity: float = Field(0.6, ge=0, le=1)


class MapBase(Schema):
    name: str = Field(..., min_length=1, max_length=120)
    description: str = ""
    frame: str = "map"
    bounds: Bounds
    walls: list[list[Point2]] = Field(
        default_factory=list, description="static wall polylines in metres"
    )
    obstacles: list[list[Point2]] = Field(
        default_factory=list, description="static obstacle polygons (shelves, pillars)"
    )
    image: MapImage | None = None
    metadata: dict[str, Any] = Field(default_factory=dict)


class MapCreate(MapBase):
    id: SlugId | None = None


class MapPatch(Schema):
    name: str | None = None
    description: str | None = None
    frame: str | None = None
    bounds: Bounds | None = None
    walls: list[list[Point2]] | None = None
    obstacles: list[list[Point2]] | None = None
    image: MapImage | None = None
    metadata: dict[str, Any] | None = None


class Map(MapBase):
    id: str
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)


class WaypointBase(Schema):
    name: str = Field(..., min_length=1, max_length=120)
    x: float
    y: float
    z: float = 0.0
    yaw: float = 0.0
    type: WaypointType = WaypointType.LOCATION
    layer: Layer = Layer.GROUND
    aliases: list[str] = Field(
        default_factory=list, description="alternative names the operator/LLM may use"
    )
    metadata: dict[str, Any] = Field(default_factory=dict)


class WaypointCreate(WaypointBase):
    id: SlugId | None = None


class WaypointPatch(Schema):
    name: str | None = None
    x: float | None = None
    y: float | None = None
    z: float | None = None
    yaw: float | None = None
    type: WaypointType | None = None
    layer: Layer | None = None
    aliases: list[str] | None = None
    metadata: dict[str, Any] | None = None


class Waypoint(WaypointBase):
    id: str
    map_id: str


class LaneBase(Schema):
    from_id: str
    to_id: str
    bidirectional: bool = True
    speed_limit: float | None = Field(None, gt=0, description="m/s")
    width: float | None = Field(None, gt=0, description="usable width in metres")
    layer: Layer = Layer.GROUND
    altitude: float | None = Field(None, description="flight altitude for air lanes (m)")
    closed: bool = False
    name: str = ""
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _distinct_ends(self) -> LaneBase:
        if self.from_id == self.to_id:
            raise ValueError("a lane must connect two different waypoints")
        return self


class LaneCreate(LaneBase):
    id: SlugId | None = None


class LanePatch(Schema):
    bidirectional: bool | None = None
    speed_limit: float | None = None
    width: float | None = None
    layer: Layer | None = None
    altitude: float | None = None
    closed: bool | None = None
    name: str | None = None
    metadata: dict[str, Any] | None = None


class Lane(LaneBase):
    id: str
    map_id: str


class ZoneBase(Schema):
    name: str = Field(..., min_length=1, max_length=120)
    type: ZoneType
    polygon: list[Point2] = Field(..., min_length=3)
    speed_limit: float | None = Field(None, gt=0)
    allowed_fleets: list[str] = Field(
        default_factory=list,
        description="restricted/no_fly: fleets allowed inside; fleet_boundary: fleets confined here",
    )
    layer: Layer | None = Field(None, description="None = applies to every layer")
    metadata: dict[str, Any] = Field(default_factory=dict)


class ZoneCreate(ZoneBase):
    id: SlugId | None = None


class ZonePatch(Schema):
    name: str | None = None
    type: ZoneType | None = None
    polygon: list[Point2] | None = None
    speed_limit: float | None = None
    allowed_fleets: list[str] | None = None
    layer: Layer | None = None
    metadata: dict[str, Any] | None = None


class Zone(ZoneBase):
    id: str
    map_id: str


class MapDetail(Map):
    """A map with its full navigation graph and zones."""

    waypoints: list[Waypoint] = Field(default_factory=list)
    lanes: list[Lane] = Field(default_factory=list)
    zones: list[Zone] = Field(default_factory=list)


class MapSeed(MapCreate):
    """On-disk seed format (config/maps/*.json)."""

    waypoints: list[WaypointCreate] = Field(default_factory=list)
    lanes: list[LaneCreate] = Field(default_factory=list)
    zones: list[ZoneCreate] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Fleets and robots
# ---------------------------------------------------------------------------


class Footprint(BaseModel):
    shape: Literal["circle", "rectangle"] = "circle"
    radius: float = Field(0.35, gt=0, description="circle radius (m)")
    length: float | None = Field(None, gt=0)
    width: float | None = Field(None, gt=0)

    @property
    def effective_radius(self) -> float:
        if self.shape == "rectangle" and self.length and self.width:
            return 0.5 * (self.length**2 + self.width**2) ** 0.5
        return self.radius

    @property
    def effective_width(self) -> float:
        if self.shape == "rectangle" and self.width:
            return self.width
        return 2 * self.radius


class MotionLimits(BaseModel):
    max_speed: float = Field(1.0, gt=0, description="m/s")
    max_accel: float = Field(0.5, gt=0, description="m/s²")
    max_decel: float = Field(1.0, gt=0, description="m/s²")
    max_yaw_rate: float = Field(1.5, gt=0, description="rad/s")
    max_vertical_speed: float | None = Field(None, gt=0, description="UAV climb rate (m/s)")
    cruise_altitude: float | None = Field(None, gt=0, description="UAV default altitude (m)")


class BatteryPolicy(BaseModel):
    capacity_wh: float | None = Field(None, gt=0)
    min_pct: float = Field(20.0, ge=0, le=100, description="never assign work below this")
    recharge_pct: float = Field(30.0, ge=0, le=100, description="auto-charge when idle below")
    charged_pct: float = Field(95.0, ge=0, le=100, description="charging completes at")
    charge_rate_pct_per_min: float = Field(12.0, gt=0)
    drain_pct_per_min_idle: float = Field(0.1, ge=0)
    drain_pct_per_m: float = Field(0.05, ge=0)


class FleetNavigation(BaseModel):
    stack: NavStack = NavStack.KINEMATIC_SIM
    planner: str = ""
    controller: str = ""
    localization: Localization = Localization.GROUND_TRUTH


class CommunicationConfig(BaseModel):
    protocol: Protocol = Protocol.SIMULATION
    endpoint: str = Field("", description="URL / broker / ROS domain, protocol-specific")
    namespace: str = Field("", description="ROS 2 namespace, e.g. /ugv_01")
    params: dict[str, Any] = Field(default_factory=dict)


class FleetBase(Schema):
    name: str = Field(..., min_length=1, max_length=120)
    robot_type: RobotType
    description: str = ""
    color: str = Field("#38bdf8", pattern=r"^#[0-9a-fA-F]{6}$")
    capabilities: list[str] = Field(default_factory=lambda: ["navigate"])
    navigation: FleetNavigation = Field(default_factory=FleetNavigation)
    footprint: Footprint = Field(default_factory=Footprint)
    limits: MotionLimits = Field(default_factory=MotionLimits)
    battery: BatteryPolicy = Field(default_factory=BatteryPolicy)
    charging_required: bool = True
    map_ids: list[str] = Field(default_factory=list, description="maps this fleet may operate on")
    layer: Layer = Layer.GROUND
    communication: CommunicationConfig = Field(default_factory=CommunicationConfig)
    priority: int = Field(5, ge=0, le=9, description="default traffic priority")
    config: dict[str, Any] = Field(default_factory=dict)

    @field_validator("capabilities")
    @classmethod
    def _caps(cls, v: list[str]) -> list[str]:
        out = []
        for cap in v:
            cap = slugify(cap)
            if cap not in out:
                out.append(cap)
        return out


class FleetCreate(FleetBase):
    id: SlugId | None = None


class FleetPatch(Schema):
    name: str | None = None
    description: str | None = None
    color: str | None = Field(None, pattern=r"^#[0-9a-fA-F]{6}$")
    capabilities: list[str] | None = None
    navigation: FleetNavigation | None = None
    footprint: Footprint | None = None
    limits: MotionLimits | None = None
    battery: BatteryPolicy | None = None
    charging_required: bool | None = None
    map_ids: list[str] | None = None
    communication: CommunicationConfig | None = None
    priority: int | None = Field(None, ge=0, le=9)
    config: dict[str, Any] | None = None


class Fleet(FleetBase):
    id: str
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)


class RobotNavigation(BaseModel):
    stack: NavStack | None = None  # None → fleet default
    namespace: str = ""
    map_id: str | None = None
    frame: str = "map"
    base_frame: str = "base_link"
    odom_source: str = "odom"
    localization: Localization | None = None
    sensors: list[str] = Field(default_factory=list)


class PhysicalSpec(BaseModel):
    footprint: Footprint | None = None
    length: float | None = Field(None, gt=0)
    width: float | None = Field(None, gt=0)
    height: float | None = Field(None, gt=0)
    max_speed: float | None = Field(None, gt=0)
    max_accel: float | None = Field(None, gt=0)
    turning_radius: float | None = Field(None, ge=0)
    payload_kg: float | None = Field(None, ge=0)
    battery_wh: float | None = Field(None, gt=0)
    charge_time_min: float | None = Field(None, gt=0)
    operating_time_min: float | None = Field(None, gt=0)


class SpawnConfig(BaseModel):
    waypoint_id: str | None = None
    pose: Pose | None = None
    battery_pct: float = Field(100.0, ge=0, le=100)


class RobotBase(Schema):
    name: str = Field(..., min_length=1, max_length=120)
    fleet_id: str
    manufacturer: str = ""
    model: str = ""
    robot_type: RobotType | None = None  # None → fleet's robot_type
    capabilities: list[str] | None = None  # None → fleet capabilities
    navigation: RobotNavigation = Field(default_factory=RobotNavigation)
    physical: PhysicalSpec = Field(default_factory=PhysicalSpec)
    communication: CommunicationConfig | None = None  # None → fleet default
    spawn: SpawnConfig = Field(default_factory=SpawnConfig)
    enabled: bool = True
    metadata: dict[str, Any] = Field(default_factory=dict)


class RobotCreate(RobotBase):
    id: SlugId | None = None


class RobotPatch(Schema):
    name: str | None = None
    fleet_id: str | None = None
    manufacturer: str | None = None
    model: str | None = None
    capabilities: list[str] | None = None
    navigation: RobotNavigation | None = None
    physical: PhysicalSpec | None = None
    communication: CommunicationConfig | None = None
    spawn: SpawnConfig | None = None
    enabled: bool | None = None
    metadata: dict[str, Any] | None = None


class Robot(RobotBase):
    id: str
    created_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)


class EffectiveRobotConfig(BaseModel):
    """Robot config with fleet defaults resolved — what the core actually uses."""

    robot_type: RobotType
    capabilities: list[str]
    map_id: str | None
    layer: Layer
    footprint: Footprint
    max_speed: float
    max_accel: float
    max_decel: float
    max_yaw_rate: float
    cruise_altitude: float | None
    max_vertical_speed: float | None
    payload_kg: float | None
    communication: CommunicationConfig
    nav_stack: NavStack
    localization: Localization
    priority: int
    battery: BatteryPolicy


# ---------------------------------------------------------------------------
# Live robot state
# ---------------------------------------------------------------------------


class Velocity(BaseModel):
    linear: float = 0.0
    angular: float = 0.0
    vertical: float = 0.0


class RobotHealth(BaseModel):
    """None = the adapter does not report this. Never synthesised."""

    cpu_pct: float | None = None
    gpu_pct: float | None = None
    temperature_c: float | None = None
    network: str | None = None
    latency_ms: float | None = None
    localization: str | None = None  # ok | degraded | lost | ground_truth
    navigation: str | None = None  # ok | unavailable | error
    sensors: dict[str, str] = Field(default_factory=dict)


class RobotState(BaseModel):
    robot_id: str
    fleet_id: str
    map_id: str | None = None
    online: bool = False
    connection: Literal["disconnected", "connecting", "connected", "error"] = "disconnected"
    connection_detail: str = ""
    mode: RobotMode = RobotMode.OFFLINE
    pose: Pose = Field(default_factory=Pose)
    velocity: Velocity = Field(default_factory=Velocity)
    battery_pct: float | None = None
    charging: bool = False
    e_stop: bool = False
    current_task_id: str | None = None
    queue: list[str] = Field(default_factory=list, description="queued task ids")
    current_waypoint: str | None = Field(None, description="graph node the robot is at")
    destination: str | None = None
    route: list[str] = Field(default_factory=list, description="remaining waypoint ids")
    path: list[Point2] = Field(default_factory=list, description="remaining path geometry")
    route_progress: float | None = None
    eta_s: float | None = None
    status_reason: str = ""
    health: RobotHealth = Field(default_factory=RobotHealth)
    adapter: str = ""
    updated_at: float = Field(default_factory=time.time)


# ---------------------------------------------------------------------------
# Tasks
# ---------------------------------------------------------------------------


class TaskRequirements(BaseModel):
    capabilities: list[str] = Field(default_factory=list)
    robot_type: RobotType | None = None
    fleet_id: str | None = None
    robot_id: str | None = Field(None, description="pin to one robot (operator's choice)")
    payload_kg: float | None = Field(None, ge=0)


class TaskTrace(BaseModel):
    """Where the task came from — operator, UI, LLM mission, system."""

    source: Literal["operator", "llm", "api", "system", "legacy_rmf"] = "api"
    command: str | None = None
    mission_id: str | None = None
    tool: str | None = None
    reason: str | None = None


class TaskCreate(Schema):
    type: TaskType
    params: dict[str, Any] = Field(default_factory=dict)
    priority: int = Field(5, ge=0, le=9)
    requirements: TaskRequirements = Field(default_factory=TaskRequirements)
    map_id: str | None = None
    created_by: str = "operator"
    trace: TaskTrace = Field(default_factory=TaskTrace)
    allow_restricted: bool = Field(False, description="only honoured after operator confirmation")


class TaskStep(BaseModel):
    kind: Literal["go_to", "action"]
    label: str
    target: str | None = None  # waypoint id (resolved at execution when zone-based)
    candidates: list[str] = Field(
        default_factory=list, description="zone targets: the free one is chosen at execution time"
    )
    zone_id: str | None = None
    action: str | None = None
    duration_s: float | None = None
    status: Literal["pending", "active", "done", "failed", "skipped"] = "pending"
    detail: str = ""
    started_at: float | None = None
    finished_at: float | None = None


class AllocationCandidate(BaseModel):
    robot_id: str
    eligible: bool
    score: float | None = None
    reasons: list[str] = Field(default_factory=list)
    estimates: dict[str, Any] = Field(default_factory=dict)


class Allocation(BaseModel):
    selected: str | None = None
    explanation: str = ""
    candidates: list[AllocationCandidate] = Field(default_factory=list)
    at: float = Field(default_factory=time.time)


class TaskHistoryEntry(BaseModel):
    ts: float = Field(default_factory=time.time)
    status: TaskStatus | None = None
    message: str


class Task(BaseModel):
    model_config = ConfigDict(use_enum_values=True)

    id: str
    type: TaskType
    params: dict[str, Any] = Field(default_factory=dict)
    priority: int = 5
    requirements: TaskRequirements = Field(default_factory=TaskRequirements)
    map_id: str | None = None
    created_by: str = "operator"
    trace: TaskTrace = Field(default_factory=TaskTrace)
    allow_restricted: bool = False
    status: TaskStatus = TaskStatus.QUEUED
    status_reason: str = ""
    assigned_fleet: str | None = None
    assigned_robot: str | None = None
    allocation: Allocation | None = None
    steps: list[TaskStep] = Field(default_factory=list)
    current_step: int = 0
    progress: float = 0.0
    created_at: float = Field(default_factory=time.time)
    assigned_at: float | None = None
    started_at: float | None = None
    completed_at: float | None = None
    history: list[TaskHistoryEntry] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Traffic
# ---------------------------------------------------------------------------


class Reservation(BaseModel):
    resource: str  # "node:<waypoint>" | "lane:<lane>"
    kind: Literal["node", "lane"]
    element_id: str
    map_id: str
    robot_id: str
    since: float


class ItineraryEntry(BaseModel):
    resource: str
    kind: Literal["node", "lane"]
    element_id: str
    t_enter: float
    t_exit: float


class Itinerary(BaseModel):
    robot_id: str
    map_id: str
    route: list[str]
    entries: list[ItineraryEntry]
    eta: float | None = None
    planned_at: float = Field(default_factory=time.time)


class ConflictKind(StrEnum):
    SAME_LANE = "same_lane"
    HEAD_ON = "head_on"
    INTERSECTION = "intersection"
    CROSSING = "crossing"
    BOTTLENECK = "bottleneck"
    CLEARANCE = "clearance"
    DESTINATION = "destination"
    DEADLOCK = "deadlock"


class ConflictResolution(BaseModel):
    action: Literal["delay", "reroute", "make_way", "priority", "operator", "none"]
    robot_id: str | None = None
    delay_s: float | None = None
    message: str


class Conflict(BaseModel):
    id: str
    kind: ConflictKind
    map_id: str
    robots: list[str]
    element_id: str
    location_name: str
    point: Point2
    predicted_at_s: float | None = Field(None, description="seconds from detection")
    status: Literal["predicted", "active", "resolved"] = "predicted"
    message: str
    resolution: ConflictResolution | None = None
    detected_at: float = Field(default_factory=time.time)
    resolved_at: float | None = None


class WaitInfo(BaseModel):
    robot_id: str
    resource: str
    element_id: str
    holder: str | None
    reason: str
    since: float


class TrafficState(BaseModel):
    reservations: list[Reservation] = Field(default_factory=list)
    itineraries: list[Itinerary] = Field(default_factory=list)
    conflicts: list[Conflict] = Field(default_factory=list)
    waits: list[WaitInfo] = Field(default_factory=list)
    precedences: list[dict[str, Any]] = Field(default_factory=list)


# ---------------------------------------------------------------------------
# Events, alerts, confirmations
# ---------------------------------------------------------------------------


class EventType(StrEnum):
    ROBOT_REGISTERED = "ROBOT_REGISTERED"
    ROBOT_UPDATED = "ROBOT_UPDATED"
    ROBOT_REMOVED = "ROBOT_REMOVED"
    ROBOT_CONNECTED = "ROBOT_CONNECTED"
    ROBOT_DISCONNECTED = "ROBOT_DISCONNECTED"
    ROBOT_BATTERY_LOW = "ROBOT_BATTERY_LOW"
    ROBOT_TASK_ASSIGNED = "ROBOT_TASK_ASSIGNED"
    ROBOT_TASK_STARTED = "ROBOT_TASK_STARTED"
    ROBOT_TASK_COMPLETED = "ROBOT_TASK_COMPLETED"
    ROBOT_TASK_FAILED = "ROBOT_TASK_FAILED"
    ROBOT_ARRIVED = "ROBOT_ARRIVED"
    ROBOT_ENTERED_RESTRICTED_ZONE = "ROBOT_ENTERED_RESTRICTED_ZONE"
    FLEET_CREATED = "FLEET_CREATED"
    FLEET_UPDATED = "FLEET_UPDATED"
    FLEET_REMOVED = "FLEET_REMOVED"
    MAP_UPDATED = "MAP_UPDATED"
    TASK_CREATED = "TASK_CREATED"
    TASK_STATUS_CHANGED = "TASK_STATUS_CHANGED"
    TASK_UNASSIGNABLE = "TASK_UNASSIGNABLE"
    TRAFFIC_CONFLICT_DETECTED = "TRAFFIC_CONFLICT_DETECTED"
    TRAFFIC_CONFLICT_RESOLVED = "TRAFFIC_CONFLICT_RESOLVED"
    TRAFFIC_WAIT = "TRAFFIC_WAIT"
    TRAFFIC_DEADLOCK = "TRAFFIC_DEADLOCK"
    ROUTE_PLANNED = "ROUTE_PLANNED"
    ROUTE_CHANGED = "ROUTE_CHANGED"
    NAVIGATION_FAILED = "NAVIGATION_FAILED"
    LOCALIZATION_LOST = "LOCALIZATION_LOST"
    SAFETY_STOP = "SAFETY_STOP"
    EMERGENCY_STOP = "EMERGENCY_STOP"
    EMERGENCY_STOP_RELEASED = "EMERGENCY_STOP_RELEASED"
    CONFIRMATION_REQUESTED = "CONFIRMATION_REQUESTED"
    CONFIRMATION_RESOLVED = "CONFIRMATION_RESOLVED"
    SIMULATION = "SIMULATION"
    SYSTEM = "SYSTEM"


class Event(BaseModel):
    model_config = ConfigDict(use_enum_values=True)

    id: int
    ts: float
    type: EventType
    severity: Severity = Severity.INFO
    message: str
    robot_id: str | None = None
    fleet_id: str | None = None
    task_id: str | None = None
    map_id: str | None = None
    data: dict[str, Any] = Field(default_factory=dict)


class Alert(BaseModel):
    id: str
    key: str  # dedupe key, e.g. "battery_low:ugv_01"
    severity: Severity
    title: str
    message: str
    robot_id: str | None = None
    task_id: str | None = None
    status: Literal["active", "acknowledged", "resolved"] = "active"
    raised_at: float = Field(default_factory=time.time)
    updated_at: float = Field(default_factory=time.time)


class PendingAction(BaseModel):
    id: str
    kind: str
    summary: str
    detail: str = ""
    params: dict[str, Any] = Field(default_factory=dict)
    requested_by: str = "operator"
    trace: TaskTrace = Field(default_factory=TaskTrace)
    status: Literal["pending", "confirmed", "rejected", "expired", "executed", "failed"] = "pending"
    result: Any = None
    created_at: float = Field(default_factory=time.time)
    expires_at: float
    resolved_at: float | None = None
