#!/usr/bin/env python3
"""
simulation/gazebo/generate_world.py — build the Gazebo world from a Nayantra map.

The map (config/maps/gazebo_warehouse.json) is the single source of truth for
where walls and shelves are. This script turns its `walls` polylines and
axis-aligned `obstacles` rectangles into SDF boxes, so the world the robots
physically drive in and the world model the core plans over cannot drift apart.

    python simulation/gazebo/generate_world.py            # rewrite the world
    python simulation/gazebo/generate_world.py --check    # exit 1 if it is stale
"""

from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent.parent
DEFAULT_MAP = REPO / "config" / "maps" / "gazebo_warehouse.json"
DEFAULT_OUT = HERE / "worlds" / "nayantra_warehouse.sdf"
WORLD_NAME = "nayantra_warehouse"
WALL_THICKNESS = 0.2
WALL_HEIGHT = 2.0
SHELF_HEIGHT = 2.2

_HEADER = """<?xml version="1.0" ?>
<!-- GENERATED by simulation/gazebo/generate_world.py from {source}. Do not edit. -->
<sdf version="1.9">
  <world name="{name}">
    <physics name="fast" type="ignored">
      <max_step_size>0.004</max_step_size>
      <real_time_factor>1.0</real_time_factor>
    </physics>
    <plugin filename="gz-sim-physics-system" name="gz::sim::systems::Physics"/>
    <plugin filename="gz-sim-user-commands-system" name="gz::sim::systems::UserCommands"/>
    <plugin filename="gz-sim-scene-broadcaster-system" name="gz::sim::systems::SceneBroadcaster"/>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
    <gravity>0 0 -9.8</gravity>
    <scene>
      <ambient>0.6 0.6 0.6 1</ambient>
      <background>0.75 0.8 0.85 1</background>
    </scene>
    <light type="directional" name="sun">
      <cast_shadows>true</cast_shadows>
      <pose>0 0 10 0 0 0</pose>
      <diffuse>0.9 0.9 0.9 1</diffuse>
      <specular>0.2 0.2 0.2 1</specular>
      <direction>-0.4 0.2 -1</direction>
    </light>
    <model name="ground">
      <static>true</static>
      <link name="link">
        <collision name="collision">
          <geometry><plane><normal>0 0 1</normal><size>{gx:.2f} {gy:.2f}</size></plane></geometry>
        </collision>
        <visual name="visual">
          <geometry><plane><normal>0 0 1</normal><size>{gx:.2f} {gy:.2f}</size></plane></geometry>
          <material><ambient>0.55 0.55 0.55 1</ambient><diffuse>0.6 0.6 0.6 1</diffuse></material>
        </visual>
      </link>
    </model>
"""

_BOX = """    <model name="{name}">
      <static>true</static>
      <pose>{x:.4f} {y:.4f} {z:.4f} 0 0 {yaw:.6f}</pose>
      <link name="link">
        <collision name="collision"><geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry></collision>
        <visual name="visual">
          <geometry><box><size>{sx:.4f} {sy:.4f} {sz:.4f}</size></box></geometry>
          <material><ambient>{rgb} 1</ambient><diffuse>{rgb} 1</diffuse></material>
        </visual>
      </link>
    </model>
"""


def _box(name: str, cx: float, cy: float, sx: float, sy: float, sz: float, yaw: float, rgb: str):
    return _BOX.format(name=name, x=cx, y=cy, z=sz / 2, yaw=yaw, sx=sx, sy=sy, sz=sz, rgb=rgb)


def axis_aligned_rect(poly: list[list[float]]) -> tuple[float, float, float, float]:
    """(x0, x1, y0, y1) of a rectangle given as four corners."""
    xs, ys = sorted({p[0] for p in poly}), sorted({p[1] for p in poly})
    if len(poly) != 4 or len(xs) != 2 or len(ys) != 2:
        raise ValueError(f"only axis-aligned rectangles are supported as obstacles: {poly}")
    return xs[0], xs[1], ys[0], ys[1]


def build_world(map_data: dict) -> str:
    b = map_data["bounds"]
    parts = [
        _HEADER.format(
            source="config/maps/" + map_data["id"] + ".json",
            name=WORLD_NAME,
            gx=(b["max_x"] - b["min_x"]) + 20,
            gy=(b["max_y"] - b["min_y"]) + 20,
        )
    ]
    n = 0
    for line in map_data.get("walls", []):
        for (x0, y0), (x1, y1) in zip(line, line[1:], strict=False):
            length = math.hypot(x1 - x0, y1 - y0)
            if length == 0:
                continue
            n += 1
            parts.append(
                _box(
                    f"wall_{n}",
                    (x0 + x1) / 2,
                    (y0 + y1) / 2,
                    length + WALL_THICKNESS,
                    WALL_THICKNESS,
                    WALL_HEIGHT,
                    math.atan2(y1 - y0, x1 - x0),
                    "0.8 0.8 0.78",
                )
            )
    for i, poly in enumerate(map_data.get("obstacles", []), start=1):
        x0, x1, y0, y1 = axis_aligned_rect(poly)
        parts.append(
            _box(
                f"shelf_{i}",
                (x0 + x1) / 2,
                (y0 + y1) / 2,
                x1 - x0,
                y1 - y0,
                SHELF_HEIGHT,
                0.0,
                "0.85 0.45 0.1",
            )
        )
    parts.append("  </world>\n</sdf>\n")
    return "".join(parts)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Build the Gazebo world from a Nayantra map.")
    ap.add_argument("--map", type=Path, default=DEFAULT_MAP)
    ap.add_argument("--out", type=Path, default=DEFAULT_OUT)
    ap.add_argument("--check", action="store_true", help="fail if the committed world is stale")
    args = ap.parse_args(argv)
    world = build_world(json.loads(args.map.read_text(encoding="utf-8")))
    if args.check:
        current = args.out.read_text(encoding="utf-8") if args.out.exists() else ""
        if current.replace("\r\n", "\n") != world:
            print(f"{args.out} is stale; run generate_world.py", file=sys.stderr)
            return 1
        return 0
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(world, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
